<?php
/**
 * Preset: Bootstrap Default
 * Category: Clean
 * Description: Stock Bootstrap 5.3 with no customizations — a neutral baseline to fork new themes from.
 * Tags: light, baseline, bootstrap, neutral, stock
 * Mode: light
 * Author: UserSpice Customizer Theme
 */
return array (
  'us-menu-custom-bg' => '#3a5e8c',
  'us-menu-custom-text' => 'rgba(255, 255, 255, 0.85)',
  'us-menu-custom-hover-bg' => '#4a6e9c',
  'us-menu-custom-hover-text' => '#ffffff',
  'us-menu-custom-active-bg' => '#264e7c',
  'us-menu-custom-active-text' => '#ffffff',
  'us-menu-custom-divider' => 'rgba(255, 255, 255, 0.2)',
  'us-menu-custom-submenu-border' => '#2d5580',
  'primary' => '#0d6efd',
  'primary-hover' => '#0b5ed7',
  'primary-text-emphasis' => '#084298',
  'primary-bg-subtle' => '#cfe2ff',
  'primary-border-subtle' => '#b6d4fe',
  'secondary' => '#6c757d',
  'secondary-hover' => '#5c636a',
  'secondary-text-emphasis' => '#41464b',
  'secondary-bg-subtle' => '#e2e3e5',
  'secondary-border-subtle' => '#d3d4d5',
  'success' => '#198754',
  'success-hover' => '#157347',
  'success-text-emphasis' => '#0f5132',
  'success-bg-subtle' => '#d1e7dd',
  'success-border-subtle' => '#badbcc',
  'info' => '#0dcaf0',
  'info-hover' => '#31d2f2',
  'info-text-emphasis' => '#055160',
  'info-bg-subtle' => '#cff4fc',
  'info-border-subtle' => '#b6effb',
  'warning' => '#ffc107',
  'warning-hover' => '#ffca2c',
  'warning-text-emphasis' => '#664d03',
  'warning-bg-subtle' => '#fff3cd',
  'warning-border-subtle' => '#ffecb5',
  'danger' => '#dc3545',
  'danger-hover' => '#bb2d3b',
  'danger-text-emphasis' => '#842029',
  'danger-bg-subtle' => '#f8d7da',
  'danger-border-subtle' => '#f5c2c7',
  'light' => '#f8f9fa',
  'light-hover' => '#d3d4d5',
  'light-text-emphasis' => '#636464',
  'light-bg-subtle' => '#fefefe',
  'light-border-subtle' => '#fdfdfe',
  'dark' => '#212529',
  'dark-hover' => '#1c1f23',
  'dark-text-emphasis' => '#141619',
  'dark-bg-subtle' => '#d3d3d4',
  'dark-border-subtle' => '#bcbebf',
  'body-color' => '#212529',
  'body-bg' => '#ffffff',
  'border-color' => '#dee2e6',
  'form-control-bg' => '#ffffff',
  'secondary-color' => '#6c757d',
  'tertiary-color' => '#9aa0a6',
  'emphasis-color' => '#000000',
  'secondary-bg' => '#e9ecef',
  'tertiary-bg' => '#f8f9fa',
  'font-sans-serif' => 'system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "Liberation Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
  'font-monospace' => 'SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  'font-size-base' => '1rem',
  'font-weight-normal' => '400',
  'font-weight-bold' => '700',
  'line-height-base' => '1.5',
  'headings-font-family' => 'var(--bs-font-sans-serif)',
  'headings-font-weight' => '500',
  'headings-line-height' => '1.2',
  'headings-color' => 'inherit',
  'h1-font-size' => 'calc(1.375rem + 1.5vw)',
  'h2-font-size' => 'calc(1.325rem + 0.9vw)',
  'h3-font-size' => 'calc(1.3rem + 0.6vw)',
  'h4-font-size' => 'calc(1.275rem + 0.3vw)',
  'h5-font-size' => '1.25rem',
  'h6-font-size' => '1rem',
  'border-radius' => '0.375rem',
  'border-radius-sm' => '0.25rem',
  'border-radius-lg' => '0.5rem',
  'border-radius-xl' => '1rem',
  'border-radius-2xl' => '2rem',
  'border-radius-pill' => '50rem',
  'box-shadow' => '0 0.5rem 1rem rgba(0, 0, 0, 0.15)',
  'box-shadow-sm' => '0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)',
  'box-shadow-lg' => '0 1rem 3rem rgba(0, 0, 0, 0.175)',
  'card-border-radius' => 'var(--bs-border-radius)',
  'card-border-color' => 'var(--bs-border-color)',
  'card-box-shadow' => 'none',
  'card-cap-bg' => 'rgba(0, 0, 0, 0.03)',
  'input-bg' => 'var(--bs-body-bg)',
  'input-color' => 'var(--bs-body-color)',
  'input-border-color' => 'var(--bs-border-color)',
  'input-focus-border-color' => 'var(--bs-primary)',
  'input-focus-box-shadow' => '0 0 0 0.25rem rgba(var(--bs-primary-rgb), 0.25)',
  'input-focus-bg' => '#ffffff',
  'input-focus-color' => '#212529',
  'navbar-light-color' => 'rgba(0, 0, 0, 0.55)',
  'navbar-light-hover-color' => 'rgba(0, 0, 0, 0.7)',
  'navbar-dark-color' => 'rgba(255, 255, 255, 0.55)',
  'navbar-dark-hover-color' => 'rgba(255, 255, 255, 0.75)',
);
