<?php
/**
 * Preset: Bootstrap Default - Dark
 * Category: Clean
 * Description: Stock Bootstrap 5.3 dark mode with no customizations — a neutral dark baseline to fork new themes from.
 * Tags: dark, baseline, bootstrap, neutral, stock
 * Mode: dark
 * Author: UserSpice Customizer Theme
 */
return array (
  'us-menu-custom-bg' => '#212529',
  'us-menu-custom-text' => 'rgba(255, 255, 255, 0.55)',
  'us-menu-custom-hover-bg' => '#2b3035',
  'us-menu-custom-hover-text' => 'rgba(255, 255, 255, 0.75)',
  'us-menu-custom-active-bg' => '#0d6efd',
  'us-menu-custom-active-text' => '#ffffff',
  'us-menu-custom-divider' => 'rgba(255, 255, 255, 0.15)',
  'us-menu-custom-submenu-border' => '#495057',
  'primary' => '#0d6efd',
  'primary-hover' => '#0b5ed7',
  'primary-text-emphasis' => '#6ea8fe',
  'primary-bg-subtle' => '#031633',
  'primary-border-subtle' => '#084298',
  'secondary' => '#6c757d',
  'secondary-hover' => '#5c636a',
  'secondary-text-emphasis' => '#a7acb1',
  'secondary-bg-subtle' => '#161719',
  'secondary-border-subtle' => '#41464b',
  'success' => '#198754',
  'success-hover' => '#157347',
  'success-text-emphasis' => '#75b798',
  'success-bg-subtle' => '#051b11',
  'success-border-subtle' => '#0f5132',
  'info' => '#0dcaf0',
  'info-hover' => '#31d2f2',
  'info-text-emphasis' => '#6edff6',
  'info-bg-subtle' => '#032830',
  'info-border-subtle' => '#055160',
  'warning' => '#ffc107',
  'warning-hover' => '#ffca2c',
  'warning-text-emphasis' => '#ffda6a',
  'warning-bg-subtle' => '#332701',
  'warning-border-subtle' => '#664d03',
  'danger' => '#dc3545',
  'danger-hover' => '#bb2d3b',
  'danger-text-emphasis' => '#ea868f',
  'danger-bg-subtle' => '#2c0b0e',
  'danger-border-subtle' => '#842029',
  'light' => '#f8f9fa',
  'light-hover' => '#d3d4d5',
  'light-text-emphasis' => '#f8f9fa',
  'light-bg-subtle' => '#343a40',
  'light-border-subtle' => '#495057',
  'dark' => '#212529',
  'dark-hover' => '#1c1f23',
  'dark-text-emphasis' => '#dee2e6',
  'dark-bg-subtle' => '#1a1d20',
  'dark-border-subtle' => '#343a40',
  'body-color' => '#dee2e6',
  'body-bg' => '#212529',
  'border-color' => '#495057',
  'form-control-bg' => '#212529',
  'secondary-color' => '#afb3b7',
  'tertiary-color' => '#808488',
  'emphasis-color' => '#ffffff',
  'secondary-bg' => '#343a40',
  'tertiary-bg' => '#2b3035',
  'font-sans-serif' => 'system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "Liberation Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
  'font-monospace' => 'SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  'font-size-base' => '1rem',
  'font-weight-normal' => '400',
  'font-weight-bold' => '700',
  'line-height-base' => '1.5',
  'headings-font-family' => 'var(--bs-font-sans-serif)',
  'headings-font-weight' => '500',
  'headings-line-height' => '1.2',
  'headings-color' => 'inherit',
  'h1-font-size' => 'calc(1.375rem + 1.5vw)',
  'h2-font-size' => 'calc(1.325rem + 0.9vw)',
  'h3-font-size' => 'calc(1.3rem + 0.6vw)',
  'h4-font-size' => 'calc(1.275rem + 0.3vw)',
  'h5-font-size' => '1.25rem',
  'h6-font-size' => '1rem',
  'border-radius' => '0.375rem',
  'border-radius-sm' => '0.25rem',
  'border-radius-lg' => '0.5rem',
  'border-radius-xl' => '1rem',
  'border-radius-2xl' => '2rem',
  'border-radius-pill' => '50rem',
  'box-shadow' => '0 0.5rem 1rem rgba(0, 0, 0, 0.15)',
  'box-shadow-sm' => '0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)',
  'box-shadow-lg' => '0 1rem 3rem rgba(0, 0, 0, 0.175)',
  'card-border-radius' => 'var(--bs-border-radius)',
  'card-border-color' => 'var(--bs-border-color)',
  'card-box-shadow' => 'none',
  'card-cap-bg' => 'rgba(255, 255, 255, 0.03)',
  'input-bg' => 'var(--bs-body-bg)',
  'input-color' => 'var(--bs-body-color)',
  'input-border-color' => 'var(--bs-border-color)',
  'input-focus-border-color' => 'var(--bs-primary)',
  'input-focus-box-shadow' => '0 0 0 0.25rem rgba(var(--bs-primary-rgb), 0.25)',
  'input-focus-bg' => '#212529',
  'input-focus-color' => '#dee2e6',
  'navbar-light-color' => 'rgba(0, 0, 0, 0.55)',
  'navbar-light-hover-color' => 'rgba(0, 0, 0, 0.7)',
  'navbar-dark-color' => 'rgba(255, 255, 255, 0.55)',
  'navbar-dark-hover-color' => 'rgba(255, 255, 255, 0.75)',
  'custom_css' => "
/* === BOOTSTRAP DEFAULT - DARK === stock Bootstrap 5.3 dark mode, no decoration */
:root { color-scheme: dark; }
/* native form-control & <select> dropdown list render dark */
.form-select option, .form-control option { background-color: #212529; color: #dee2e6; }
/* Bootstrap 5.3 dark-mode link & code colors */
a:not(.btn):not(.nav-link) { color: #6ea8fe; }
a:not(.btn):not(.nav-link):hover { color: #8bb9fe; }
code { color: #e685b5; }
",
);
