<?php 
//do not edit this file! Please copy it and edit the copy. Updates may overwrite this file.


$emailSet = $db->query("SELECT * FROM email")->first();

if ($emailSet->email_login == "yourEmail@gmail.com" || $emailSet->email_login == "" || $emailSet->email_pass == "1234" || $settings->no_passwords == 1) {
    $showForgot = false;
} else {
    $showForgot = true;
}


if ($showForgot == true && $settings->registration == 1) {
    $bottomClass = "col-12 col-lg-6";
    $showBottom = true;
    $forgotClass = "";
    $regClass = "text-end";
} elseif ($showForgot == true || $settings->registration == 1) {
    $showBottom = true;
    $bottomClass = "col-12";
    $forgotClass = "text-center";
    $regClass = "text-end";
} else {
    $showBottom = false;
}
?>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<div class="container">
    <div class="card login-card shadow">
        <div class="card-body">
            <h5 class="card-title text-center mb-4"><?= $authData['login_title'] ?></h5>
            <?php if (isset($error)) { ?>
                <div class="alert alert-danger" role="alert">
                    <?php echo $error; ?>
                </div>
            <?php } ?>

            <div class="mb-3">
                <label for="username" class="form-label"><?= lang("SIGNIN_UORE") ?>:</label>
                <input type="text" class="form-control" id="username" name="username" required autofocus>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label"><?= lang("SIGNIN_PASS") ?>:</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <div class="d-grid">
                <input type="submit" class="btn btn-primary" value="Login">
            </div>
            <?php if ($showBottom) { ?>
                <div class="row p-3">
                    <?php if ($showForgot) { ?>
                        <div class="<?= $bottomClass ?> <?= $forgotClass ?>">
                            <a class="" href='<?= $us_url_root ?>users/forgot_password.php' style="text-decoration:none;"><i class="fa fa-wrench"></i> <?= lang("SIGNIN_FORGOTPASS", ""); ?></a>
                        </div>
                    <?php }

                    if ($settings->registration == 1) { ?>
                        <div class="<?= $bottomClass ?> <?= $regClass ?>">
                            <a class="" href='<?= $us_url_root ?>users/join.php' style="text-decoration:none;"><i class="fa fa-plus-square"></i> <?= lang("SIGNUP_TEXT", ""); ?></a>
                        </div>
                    <?php }
                    ?>

                </div>

            <?php } //end showBottom 
            ?>
        </div>
    </div>
</div>

<style>
    .login-card {
        max-width: 500px;
        margin: auto;
        margin-top: 10%;
    }
</style>
<script nonce="<?=htmlspecialchars($usespice_nonce ?? '')?>" src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script nonce="<?=htmlspecialchars($usespice_nonce ?? '')?>" src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>